seed_everything: 42
trainer:
  max_epochs: 30
  accelerator: "gpu"
  devices: [0]
  callbacks:
    - class_path: callbacks.callbacks.TestCallback
      init_args: {}  
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_weights_only: false
        mode: "min"
        monitor: "val_loss"
        every_n_train_steps: 0
        every_n_epochs: 1
        train_time_interval: null 
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        min_delta: 0.0
        patience: 3
        verbose: false
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: "."
        name: "h2tt_angle_0_results"                
model:
  num_classes: 2
  h_feat: 32
  n_heads: 8
  dropout: 0.1
  batch_size: 128
  learning_rate: 0.0001
data:
  h5_file: ""
  seed: 42
  batch_size: 128
  num_workers: 16
